
const TYPES = {
    AuthController: Symbol.for('AuthController'),
    AuthService: Symbol.for('AuthService'),
    UserRepository: Symbol.for('UserRepository'),
    AdminController: Symbol.for('AdminController'),
    AdminService: Symbol.for('AdminService'),
    CategoryController: Symbol.for('CategoryController'),
    CategoryService: Symbol.for('CategoryService'),
    CategoryRepository: Symbol.for('CategoryRepository'),
    CommissionRuleRepository: Symbol.for('CommissionRuleRepository'),
    ProviderController: Symbol.for('ProviderController'),
    ProviderService: Symbol.for('ProviderService'),
    ProviderRepository: Symbol.for('ProviderRepository'),
    AddressController: Symbol.for('AddressController'),
    AddressService: Symbol.for('AddressService'),
    AddressRepository: Symbol.for('AddressRepository'),
    BookingController: Symbol.for('BookingController'),
    BookingService: Symbol.for('BookingService'),
    BookingRepository: Symbol.for('BookingRepository'),
    PaymentRepository: Symbol.for('PaymentRepository'),
    ServiceController: Symbol.for('ServiceController'),
    ServiceService: Symbol.for('ServiceService'),
    ServiceRepository: Symbol.for('ServiceRepository'),
    MessageRepository: Symbol.for('MessageRepository'),
    WalletController: Symbol.for('WalletController'),
    WalletService: Symbol.for('WalletService'),
    WalletRepository: Symbol.for('WalletRepository'),
    ReviewController: Symbol.for('ReviewerController'),
    ReviewService: Symbol.for('ReviewService'),
    ReviewRepository: Symbol.for('ReviewRepository'),
    SubscriptionPlanController: Symbol.for('SubscriptionPlanController'),
    SubscriptionPlanService: Symbol.for('SubscriptionPlanService'),
    SubscriptionPlanRepository: Symbol.for('SubscriptionPlanRepository'),
    MessageController: Symbol.for('MessageController'),

}

export default TYPES